#pragma once 

#include "systems/AsteroidSystem.hpp"
#include "systems/CameraSystem.hpp"
#include "systems/DamageSystem.hpp"
#include "systems/GravitySystem.hpp"
#include "systems/InteractableWithPlanetSystem.hpp"
#include "systems/LifetimeSystem.hpp"
#include "systems/OrbitSystem.hpp"
#include "systems/PhysicsSystem.hpp"
#include "systems/PlayerSystem.hpp"
#include "systems/RenderDebugSystem.hpp"
#include "systems/RenderSystem.hpp"
#include "systems/RotationSystem.hpp"
#include "systems/TargetingSystem.hpp"
#include "systems/UISystem.hpp"
