#pragma once

#include "components/AsteroidComponent.hpp"
#include "components/BodyComponent.hpp"
#include "components/CameraComponent.hpp"
#include "components/CollidableComponent.hpp"
#include "components/DamageableComponent.hpp"
#include "components/GravityComponent.hpp"
#include "components/InteractableWithPlanetComponent.hpp"
#include "components/LifetimeComponent.hpp"
#include "components/PlayerComponent.hpp"
#include "components/RenderableComponent.hpp"
#include "components/ShootableComponent.hpp"
#include "components/TransformComponent.hpp"
#include "components/UIMapComponent.hpp"
